/** Default village routes from school transport fee chart (monthly charge). */
export const DEFAULT_TRANSPORT_ROUTES: { name: string; monthlyFee: number }[] = [
  { name: "Nagla Sikandar", monthlyFee: 200 },
  { name: "Nagla Beach", monthlyFee: 350 },
  { name: "Mohammdi", monthlyFee: 400 },
  { name: "Bhondela", monthlyFee: 350 },
  { name: "Nagla Dal Road", monthlyFee: 300 },
  { name: "Rudhau", monthlyFee: 400 },
  { name: "Kanchanpur/ Toola", monthlyFee: 400 },
  { name: "Sada ka Bansh", monthlyFee: 400 },
  { name: "Nagla Dal In Side", monthlyFee: 350 },
  { name: "Kheralangar", monthlyFee: 450 },
  { name: "Himmatpur", monthlyFee: 450 },
  { name: "Zarara", monthlyFee: 450 },
  { name: "Imaliya", monthlyFee: 400 },
  { name: "Mandanpur", monthlyFee: 500 },
  { name: "Madari Gari", monthlyFee: 550 },
  { name: "Babari/Dheemar", monthlyFee: 450 },
  { name: "Shri Nagar", monthlyFee: 450 },
  { name: "Pahadpur", monthlyFee: 450 },
  { name: "Pakharpura", monthlyFee: 550 },
  { name: "Mohbbali", monthlyFee: 400 },
  { name: "Jori gari", monthlyFee: 500 },
  { name: "Uttam Gari", monthlyFee: 450 },
  { name: "Nagla Doori", monthlyFee: 650 },
  { name: "Pahadipur", monthlyFee: 450 },
  { name: "Tara Nagar", monthlyFee: 500 },
  { name: "Rijawali", monthlyFee: 550 },
  { name: "Marsena", monthlyFee: 550 },
  { name: "Garh", monthlyFee: 450 },
  { name: "Galib", monthlyFee: 500 },
  { name: "Gangapur", monthlyFee: 450 },
  { name: "Nagla prem", monthlyFee: 450 },
  { name: "Shekhupur", monthlyFee: 450 },
  { name: "Pachokhra", monthlyFee: 500 },
  { name: "Nagla Kharag", monthlyFee: 500 },
  { name: "Gari Ghiroli", monthlyFee: 400 },
  { name: "Rajmal", monthlyFee: 500 },
  { name: "Nagla Suraj", monthlyFee: 550 },
  { name: "Gadi Vaisal", monthlyFee: 500 },
  { name: "Nathu Burj", monthlyFee: 550 },
  { name: "Rampur", monthlyFee: 550 },
  { name: "Chhikau", monthlyFee: 550 },
  { name: "Nagla Mawashi", monthlyFee: 500 },
  { name: "Summer Gari", monthlyFee: 550 },
  { name: "Gari gazi", monthlyFee: 600 },
  { name: "Nagla Gangaram", monthlyFee: 550 },
  { name: "Piproli", monthlyFee: 500 },
  { name: "Thalu Gari", monthlyFee: 650 },
  { name: "Dakai", monthlyFee: 600 },
  { name: "Devkheda", monthlyFee: 600 },
  { name: "Hathi Garhi", monthlyFee: 600 },
  { name: "Nagla Sirji", monthlyFee: 600 },
  { name: "Gothua", monthlyFee: 600 },
  { name: "Nagla Iswari", monthlyFee: 400 },
  { name: "Daya Gari", monthlyFee: 450 },
  { name: "Sihorgarh", monthlyFee: 700 },
  { name: "Sakrolli", monthlyFee: 650 },
  { name: "Mohammadabad", monthlyFee: 600 },
  { name: "Dhanwant", monthlyFee: 450 },
  { name: "Okhara", monthlyFee: 700 },
];
